### ISSUE TITLE
Doh, issues :0) Posting in dev works but not in prod

### ISSUE THREAD

**Issue by voodoo** [jeffkreeftmeijer/tumblr#1]
Hi, Thanks for the cool gem. I'd hoped it was because I was using it as a plugin -- but I get the same thing when I installed it as a gem.

I'm using rails 2.3.4. On a mac locally - in prod Linux Ubuntu, Slicehost.

I get a very generic error in the response from Tumblr.

<h1 style="white-space:nowrap;">Sorry!  An error has occurred.</h1>

Realllly :) Just got a reply back from tumblr - "Please reference the link below...
http://www.tumblr.com/docs/api"

Hahahaha! Not their problem and not yours either! Just thought I'd ask before digging deeper - especially because it works in dev - thought that was a big clue ... hoping maybe.

Thanks again for the response and the gem.  :Paul

---

**Comment by voodoo** [comment]
The problem is the httpary gem. 0.4.3 works but not 0.4.5

0.4.3

> > Tumblr::User.new('VALID_EMAIL', 'VALID_PWD')
> > => #<Tumblr::User:0x7fedb8b43dd8 @tumblr=LOTS_OF_TUMBLR_VARS

0.4.5

> > Tumblr::User.new('VALID_EMAIL', 'VALID_PWD')
> > => #<Tumblr::User:0x36b40ec .... @tumblr="tumblr"

Note @tumblr just equals the string 'tumblr'

Long story short, use 4.3. I'll post this over on httparty issues page. Yay issues. Yay Github. 
Thanks again!

**Comment by jeffkreeftmeijer** [comment]
Thanks a lot! I pushed a fix :)

**Comment by voodoo** [comment]
Great fix! I did not know you could do the require like that, thanks Jeff.

**Comment by jeffkreeftmeijer** [comment]
I forgot that require method is rails only. I'm trying to get the gem to run on ruby alone, so I changed the require ( http://github.com/jeffkreeftmeijer/tumblr/commit/a8f0748c9027ad9a4f38773ce7ec745c3e5ce06c )
