### ISSUE TITLE
Tumblr::Post.all parameters not working?

### ISSUE THREAD

**Issue by moQuez** [jeffkreeftmeijer/tumblr#3]
Currently I'm trying to fetch just a few of my posts from my tumblr blog.

If a try the following...

> > Tumblr::Post.all(:num => 1).size
> > => 2

You can notice that I would expect to have only 1 post returned. I've tried using other parameters and they all don't seem to work properly...

I'm using the latest version... 0.1.4...

Thanks in advance..

**Comment by fiftyandfifty** [comment]
bump.

We're seeing the same issue.

**Comment by crayment** [comment]
You can pass the options as follows to get this to work.

```
Tumblr::Post.all(:query => {:num => 1})
```

Note that there is another bug when there is only 1 result.  It does not create a hash but instead gives you array pairs.

Hopefully saves someone some time.
