### ISSUE TITLE
400 error when doing Tumblr::Post.create

### ISSUE THREAD

**Issue by matenia** [jeffkreeftmeijer/tumblr#5]
Hi, I have followed the guide and followed the api docs on the tumblr site and I had this segment of code working. 

> @postcontent = @post.content.gsub(/<\/?[^>]*>/,  "")
> 
> post = Tumblr::Post.create(:email => 'valid@email', :password => 'mypassword', :type => 'video', :embed => @post.video_html, :caption => @postcontent)

this snippet would indeed post to tumblr, but all of a sudden im getting a 400 error.
The html that's returned for the caption is valid and has been stripped. I even checked it for rogue table tags. Am i missing something?
has tumblr done an update that is affecting this?

Any help would be great. Thanks.

**Comment by maxstoller** [comment]
I'm also getting this error.

**Comment by matenia** [comment]
the thing is, it works on some posts using the above method and not on others. . . there must be a character that's being skipped within the gsub. I have sent a request to tumblr themselves to see if there are any forbidden characters when submitting via the API. I hope they get back to me soon. If I find anything else out I will post a solution.

**Comment by morrissinger** [comment]
any progress on this issue?  i am getting this error consistently when trying to create new posts?

**Comment by matenia** [comment]
https://github.com/matenia/tumblr should work ... made a few changes to the code.

**Comment by morrissinger** [comment]
thank you, kindly.  this works.

**Comment by matenia** [comment]
just another hint ... 

include ActionView::Helpers::TextHelper
  include ActionView::Helpers::SanitizeHelper
in your controller or model (in rails 2.3.8) if using rails 3 you will need to look this up.

That way to make sure it's valid and clean html (especially if you're using a wysiwyg editor) you can then do 

post = Tumblr::Post.create(:email => 'valid@email', :password => 'mypassword', :type => 'video', :embed => @post.video_html, :caption => ActionController::Base.helpers.sanitize(@post.content) 

which will sanitize the html in the controller
